basic pgsearch setup with search enabled for beers and breweries
adcousin/hops pull request #35
Opened 2020-12-02 17:10 UTC by JPS09

2020-12-02 17:36 UTC, adcousin requested changes

2020-12-02 17:36 UTC, adcousin commented on app/models/beer.rb
> +    against: %i[name alcohol_strength ibu],
On peut ajouter :
Pour `beers`
- [ ] `color` (beers.color.name)
- [ ] `style` (beer.style.name)
- [ ] `barcode` (pour la recherche par barcode dans notre db après photo)

2020-12-02 17:36 UTC, adcousin commented on app/models/beer.rb
> +      brewery: %i[name address]
On peut ajouter :
Pour `breweries`
- [ ] `country` (breweries.country.name)

2020-12-02 18:33 UTC, JPS09 commented
https://stackoverflow.com/questions/54218205/how-to-get-results-from-a-pg-search-multisearch

2020-12-03 15:35 UTC, closed without merging

2020-12-03 15:35 UTC, sbriclot commented
Some settings problems with pg search, restart installation from scratch.